name: CI/CD Pipeline

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - master  # Trigger on push to the master branch
  pull_request:
    branches:
      - master  # Trigger on pull request to the master branch

jobs:
  # CI job: Build and Test
  build-and-test:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated to the latest version
        with:
          node-version: '14'  # Specify Node.js version (change if needed)

      - name: Install dependencies
        run: npm install  # Install dependencies

      - name: Run tests
        run: npm test  # Uncomment and modify this if you have tests

  # CD job: Deploy
  deploy:
    runs-on: ubuntu-latest

    needs: build-and-test  # Ensure deploy only happens after the build job

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: npx vercel --prod --token $VERCEL_TOKEN
